
sudo: required

dist: trusty

language: cpp

services:
  - mongodb

before_script:
  - sleep 15

compiler:
  - gcc

before_install:
  - sudo pip install cpp-coveralls


install:
  - cd ApplicationServer
  - chmod +x install.sh
  - sudo ./install.sh

script:
  - ./configure --enable-gcov && make && make check
  - ctest

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

