
sudo: required

dist: trusty

language: cpp

services:
  - mongodb

before_script:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --zerocounters

compiler:
  - gcc

before_install:
  - sudo pip install cpp-coveralls


install:
  - cd ApplicationServer
  - chmod +x install.sh
  - sudo ./install.sh
- cd ${TRAVIS_BUILD_DIR}
# install latest LCOV (1.9 was failing for me) [1]
- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar xf lcov_1.11.orig.tar.gz
- sudo make -C lcov-1.11/ install
# install lcov to coveralls conversion + upload tool
- gem install coveralls-lcov
- lcov --version

script:
- cd ${TRAVIS_BUILD_DIR}
- cmake .
- make
- ctest --verbose


after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
- lcov --list coverage.info
- coveralls-lcov coverage.info

